# Generated by Django 3.1.14 on 2023-02-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='summa',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
