# Generated by Django 3.1.14 on 2023-02-17 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20230217_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='summa',
        ),
    ]
